name: Deploy to Another Repository

on:
  push:
    branches:
      - dev
      - main

jobs:
  dev:
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Clone Deploy Branch
        run: | 
          git config --global user.name "Rik"
          git config --global user.email "1439713475@qq.com"

          git clone -b dev_deploy https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/Msg-Pilot-Deploy.git target-repo
          cp -r ./node_modules ./

      - name: Build Project
        run: |
          yarn
          yarn build

      - name: Commit and Push Changes
        run: |
          cd target-repo

          cp -r ../dist ./
          cp -r ../node_modules ./
          cp -r ../apps ./
          cp ../docker-compose.yaml ./ 
          cp ../docker-compose-prod.yaml ./ 
          cp ../Dockerfile ./ 

          git add .
          git commit -m "Automated deployment $(date +'%Y-%m-%d %H:%M:%S')"
          git push https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/linyana/Msg-Pilot-Deploy.git dev_deploy

        env:
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
  main:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Clone Deploy Branch
        run: | 
          git config --global user.name "Rik"
          git config --global user.email "1439713475@qq.com"

          git clone -b main_deploy https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/Msg-Pilot-Deploy.git target-repo
          cp -r ./node_modules ./

      - name: Build Project
        run: |
          yarn
          yarn build

      - name: Commit and Push Changes
        run: |
          cd target-repo

          cp -r ../dist ./
          cp -r ../node_modules ./
          cp -r ../apps ./
          cp ../docker-compose.yaml ./ 
          cp ../docker-compose-prod.yaml ./ 
          cp ../Dockerfile ./ 

          git add .
          git commit -m "Automated deployment $(date +'%Y-%m-%d %H:%M:%S')"
          git push https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/linyana/Msg-Pilot-Deploy.git main_deploy

        env:
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}